### ISSUE TITLE
Error after installation script

### ISSUE THREAD

**Issue by deyvsonaguiar** [it-projects-llc/install-odoo#154]
I need your help, please:

Error After executed: 

root@ip-xxxxxxx:/home/ubuntu/install-odoo# sudo su - odoo -s /bin/bash -c  "/usr/local/src/odoo-source/odoo-bin -c /etc/openerp-server.conf"
Traceback (most recent call last):
  File "/usr/local/src/odoo-source/odoo-bin", line 5, in <module>
    __import__('pkg_resources').declare_namespace('odoo.addons')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2081, in declare_namespace
    declare_namespace(parent)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2046, in _handle_ns
    loader.load_module(packageName)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/usr/local/src/odoo-source/odoo/__init__.py", line 81, in <module>
    import cli
  File "/usr/local/src/odoo-source/odoo/cli/__init__.py", line 9, in <module>
    import deploy
  File "/usr/local/src/odoo-source/odoo/cli/deploy.py", line 5, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by deyvsonaguiar** [comment]
Solved: 

sudo pip install pyOpenSSL==16.2.0

Worked!
