### ISSUE TITLE
how to use this script to Install SaaS Tools

### ISSUE THREAD

**Issue by elliotxin** [it-projects-llc/install-odoo#167]
In the beginning I was fellow the instruction to change the ''install-odoo-saas.sh"files,as below
![screenshot from 2018-12-21 18-35-28](https://user-images.githubusercontent.com/3390411/50338422-374f2600-054f-11e9-88e1-c2ce1705a917.png)
after I finished this script, the odoo working properly,so i prepare to fellow the instruction to install odoo-saas, when i copy

INIT_SAAS_TOOLS_VALUE="\
--portal-create \
--server-create \
--plan-create \
--odoo-script=/usr/local/src/odoo-source/odoo-bin \
--odoo-config=/etc/openerp-server.conf \
--admin-password='${ODOO_MASTER_PASS}' \
--portal-db-name=${ODOO_DOMAIN} \
--server-db-name=server-1.${ODOO_DOMAIN} \
--plan-template-db-name=template-1.${ODOO_DOMAIN} \
--plan-clients=demo-%i.${ODOO_DOMAIN} \
"
to the shell, and execute the command like 

`- "INIT_SAAS_TOOLS=$INIT_SAAS_TOOLS_VALUE bash -x install-odoo-saas.sh"`

and this script running again like before i install odoo, and for some reason the script stopped because i already install the POSTGRESQL and make the user name "odoo"

after than i read the script and i try to enter on command in the shell as:

`- sudo su  --preserve-environment - odoo -s /bin/bash -c 'python /usr/local/src/odoo-extra-addons/it-projects-llc/odoo-saas-tools/saas.py'`

some error appear:

```
-su: /root/.bash_profile: Permission denied
2018-12-21 18:24:56
saas.py >>> Waiting for port, 127.0.0.1, 8069
2018-12-21 18:24:59
saas.py >>> Spawn, ./odoo-server --xmlrpc-port=8069 --longpolling-port=8072 --database= --db-filter=%h --workers=3 --db_user=odoo --db_password=odoo --db_port=5432 --max-cron-threads=0
2018-12-21 18:24:59
saas.py >>> Spawn pid: 1579
2018-12-21 18:24:59
saas.py >>> Waiting for port, 127.0.0.1, 8069
Traceback (most recent call last):
  File "/usr/local/src/odoo-extra-addons/it-projects-llc/odoo-saas-tools/saas.py", line 662, in <module>
    main()
  File "/usr/local/src/odoo-extra-addons/it-projects-llc/odoo-saas-tools/saas.py", line 183, in main
    pid = spawn_cmd(cmd)
  File "/usr/local/src/odoo-extra-addons/it-projects-llc/odoo-saas-tools/saas.py", line 602, in spawn_cmd
    shell=shell)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1334, in _execute_child
    os.close(errpipe_read)
OSError: [Errno 9] Bad file descriptor

2018-12-21 18:25:29
saas.py >>> KILL, 1579
```

So anyone can tell me how to install the saas-tool after install odoo?
Does my steps correct?

**Comment by altanmur** [comment]
Not change default value 'no' to 'yes'. Because is run again.

just use after install:
INIT_SAAS_TOOLS_VALUE="
--portal-create 
--server-create 
--plan-create 
--odoo-script=/usr/local/src/odoo-source/odoo-bin 
--odoo-config=/etc/openerp-server.conf 
--admin-password='${ODOO_MASTER_PASS}' 
--portal-db-name=${ODOO_DOMAIN} 
--server-db-name=server-1.${ODOO_DOMAIN} 
--plan-template-db-name=template-1.${ODOO_DOMAIN} 
--plan-clients=demo-%i.${ODOO_DOMAIN} 
"

- "INIT_SAAS_TOOLS=$INIT_SAAS_TOOLS_VALUE bash -x install-odoo-saas.sh"

I currently this position. But required su password: i can't correct password. Is not root password and not user password.

**Comment by elliotxin** [comment]
@altanmur thanks a lot, I will try it.
